# Generated by Django 4.2.1 on 2023-05-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('relacion', models.CharField(max_length=20)),
                ('asistentes', models.CharField(max_length=20)),
                ('dedicatoria', models.CharField(max_length=250)),
            ],
        ),
    ]
